site_name: Pode

nav:
  - Home: index.md
  - Release Notes: release-notes.md

  - Getting Started:
    - Installation: Getting-Started/Installation.md
    - Build Your First App: Getting-Started/FirstApp.md
    - CLI: Getting-Started/CLI.md
    - Docker: Getting-Started/Docker.md
    - Frontend: Getting-Started/Frontend.md
    - Local Modules: Getting-Started/LocalModules.md
    - Run as a Service: Getting-Started/RunAsService.md
    - Known Issues: Getting-Started/KnownIssues.md

  - Tutorials:
    - Basics: Tutorials/Basics.md
    - Threading: Tutorials/Threading.md
    - Certificates: Tutorials/Certificates.md
    - Server Restarting:
      - Overview: Tutorials/ServerRestarting/Overview.md
      - File Monitoring: Tutorials/ServerRestarting/FileMonitoring.md
      - Auto-Restarting: Tutorials/ServerRestarting/AutoRestarting.md
    - Timers: Tutorials/Timers.md
    - Schedules: Tutorials/Schedules.md
    - Shared State: Tutorials/SharedState.md
    - Modules & SnapIns: Tutorials/ImportingModules.md
    - Configuration: Tutorials/Configuration.md
    - Web & Routes:
      - Overview: Tutorials/Routes/Overview.md
      - Error Pages: Tutorials/Routes/ErrorPages.md
      - Redirecting: Tutorials/Routes/Redirecting.md
      - Web Pages: Tutorials/Routes/WebPages.md
      - Static Content: Tutorials/Routes/StaticContent.md
      - Login Page: Tutorials/Routes/LoginPage.md
      - Flash Messages: Tutorials/Routes/FlashMessages.md
      - Content Types: Tutorials/Routes/ContentTypes.md
      - Cookies: Tutorials/Routes/Cookies.md
    - Middleware:
      - Overview: Tutorials/Middleware/Overview.md
      - Access Rules: Tutorials/Middleware/AccessRules.md
      - Rate Limiting: Tutorials/Middleware/RateLimiting.md
      - Sessions: Tutorials/Middleware/Sessions.md
      - CSRF: Tutorials/Middleware/CSRF.md
    - Logging:
      - Overview: Tutorials/Logging/Overview.md
      - Terminal: Tutorials/Logging/Terminal.md
      - File: Tutorials/Logging/File.md
      - Custom: Tutorials/Logging/Custom.md
    - Authentication:
      - Overview: Tutorials/Authentication/Overview.md
      - Validators: Tutorials/Authentication/Validators.md
      - Basic: Tutorials/Authentication/Basic.md
      - Form: Tutorials/Authentication/Form.md
      - Custom: Tutorials/Authentication/Custom.md
    - View Engines:
      - Pode: Tutorials/ViewEngines/Pode.md
      - Third Party: Tutorials/ViewEngines/ThirdParty.md
    - SMTP Server: Tutorials/SmtpServer.md
    - Misc:
      - Cron Expressions: Tutorials/Misc/CronExpressions.md
      - Desktop Application: Tutorials/Misc/DesktopApp.md
      - Uploading Files: Tutorials/Misc/UploadFiles.md
      - Server Root: Tutorials/Misc/ServerRoot.md

  - Functions:
    - Core:
      - Config: Functions/Core/Config.md
      - Endware: Functions/Core/Endware.md
      - Engine: Functions/Core/Engine.md
      - Gui: Functions/Core/Gui.md
      - Handler: Functions/Core/Handler.md
      - Import: Functions/Core/Import.md
      - Listen: Functions/Core/Listen.md
      - Load: Functions/Core/Load.md
      - Logger: Functions/Core/Logger.md
      - Middleware: Functions/Core/Middleware.md
      - Route: Functions/Core/Route.md
      - Schedule: Functions/Core/Schedule.md
      - Server: Functions/Core/Server.md
      - Timer: Functions/Core/Timer.md

    - Middleware:
      - Access: Functions/Middleware/Access.md
      - Auth: Functions/Middleware/Auth.md
      - Csrf: Functions/Middleware/Csrf.md
      - Limit: Functions/Middleware/Limit.md
      - Session: Functions/Middleware/Session.md

    - Response:
      - Attach: Functions/Response/Attach.md
      - Cookie: Functions/Response/Cookie.md
      - Csv: Functions/Response/Csv.md
      - File: Functions/Response/File.md
      - Html: Functions/Response/Html.md
      - Json: Functions/Response/Json.md
      - Redirect: Functions/Response/Redirect.md
      - Status: Functions/Response/Status.md
      - Text: Functions/Response/Text.md
      - View: Functions/Response/View.md
      - Xml: Functions/Response/Xml.md

    - Utility:
      - Await: Functions/Utility/Await.md
      - Dispose: Functions/Utility/Dispose.md
      - Flash: Functions/Utility/Flash.md
      - Include: Functions/Utility/Include.md
      - Lock: Functions/Utility/Lock.md
      - Root: Functions/Utility/Root.md
      - Save: Functions/Utility/Save.md
      - State: Functions/Utility/State.md
      - Stopwatch: Functions/Utility/Stopwatch.md
      - Stream: Functions/Utility/Stream.md
      - Tcp: Functions/Utility/Tcp.md

    - Helpers:
      - Coalesce: Functions/Helpers/Coalesce.md
      - Invoke-ScriptBlock: Functions/Helpers/Invoke-ScriptBlock.md
      - Test-Empty: Functions/Helpers/Test-Empty.md
      - Test-IsPSCore: Functions/Helpers/Test-IsPSCore.md
      - Test-IsUnix: Functions/Helpers/Test-IsUnix.md
      - Test-IsWindows: Functions/Helpers/Test-IsWindows.md

theme:
  name: material
  logo: images/icon.png
  favicon: images/favicon.ico
  feature:
    tabs: true
  palette:
    primary: cyan
    accent: cyan

markdown_extensions:
  - codehilite
  - admonition
  - meta

repo_name: badgerati/pode

repo_url: https://github.com/Badgerati/Pode

extra:
  social:
    - type: github
      link: https://github.com/badgerati
    - type: twitter
      link: https://twitter.com/badgerati