name: Pode CI Coverage

on:
  push:
    branches:
    - 'master'
    - 'develop'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Invoke-Build
      shell: pwsh
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Install-Module -Name InvokeBuild -RequiredVersion '5.5.1' -Force

    - name: Run Pester Tests
      shell: pwsh
      env:
        PODE_COVERALLS_TOKEN: ${{ secrets.PODE_COVERALLS_TOKEN }}
        PODE_RUN_CODE_COVERAGE: true
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-Build Test